enabled: true
review_enabled: true
message_generation_enabled: true
# WHY Environment Variable Support
# Enable WHY variable to provide context about the reason for changes
# Usage: WHY="fix critical memory leak" git commit
use_why_variable: true
# Prompt interactively for WHY when not set (can be disabled by setting WHY="" or use_why_variable: false)
prompt_for_why: true
max_subject_length: 50
max_body_line_length: 72
skip_patterns:
  - "^WIP:"
  - "^TEMP:"
  - "^FIXUP:"
  - "^SQUASH:"
  - "^Merge branch"
  - "^Merge pull request"
# Legacy patterns (kept for backwards compatibility)
file_ignore_patterns:
  - "*.log"
  - "*.tmp"
  - "*.cache"
  - "node_modules/"
  - ".git/"
  - "dist/"
  - "build/"
  - "coverage/"
  - ".next/"
  - ".nuxt/"
  - "vendor/"
  - "target/"
  - "bin/"
  - "obj/"

# Enhanced file filtering - single consolidated list
excluded_files:
  # Lock files
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "Cargo.lock"
  - "Gemfile.lock"
  - "composer.lock"
  - "Pipfile.lock"
  - "poetry.lock"
  - "mix.lock"
  - "go.sum"
  - "pubspec.lock"
  # Generated/compiled files
  - "*.min.js"
  - "*.min.css"
  - "*.bundle.js"
  - "*.chunk.js"
  - "*.pyc"
  - "*.class"
  - "*.o"
  - "*.exe"
  - "*.dll"
  - "*.so"
  - "*.dylib"
  # Binary files
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.gif"
  - "*.bmp"
  - "*.ico"
  - "*.pdf"
  - "*.zip"
  - "*.tar.gz"
  - "*.rar"
  - "*.7z"
  - "*.mp3"
  - "*.mp4"
  - "*.avi"
  - "*.mov"
  - "*.wmv"
  - "*.flv"
  - "*.doc"
  - "*.docx"
  - "*.xls"
  - "*.xlsx"
  - "*.ppt"
  - "*.pptx"
  # Meta/log files
  - "CHANGELOG.md"
  - "CHANGELOG.txt"
  - "*.temp"

# File filtering settings
file_filtering:
  enabled: true
  detect_binary_content: true
excluded_repositories:
  - "dotfiles"
  - "temp-repo"
  - "playground"
commit_types:
  - "feat"
  - "fix"
  - "docs"
  - "style"
  - "refactor"
  - "test"
  - "chore"
  - "ci"
  - "build"
  - "perf"
  - "revert"
prompt_template: |
  Generate a commit message for repository "{repo_name}" focusing on WHY over WHAT.

  {project_context}{why_context}

  REQUIREMENTS:
  - Subject: TYPE: Brief WHY-focused description ({max_subject_length} chars max)
  - Body: Brief motivation + bullet list of major changes only
  - Body lines wrapped at {max_body_length} characters
  - Group related minor changes, omit irrelevant details
  - Use conventional commit types
  - If there are breaking changes or updates to APIs/configuration, include a separate section summarizing them.
  - Only if the commit includes both code changes and GitHub Actions (CI) changes, add a separate section summarizing the CI changes.

  STRUCTURE:
  ```
  TYPE: Why this change was needed/what problem it solves

  Brief explanation of the motivation and impact.

  * Major change 1 (group related items)
  * Major change 2
  * Major change 3 (omit trivial formatting/refactoring)

  Authors and coauthors:
    - {author_name} <{author_email}>

  ```

  EXAMPLES:
  ```
  FEAT: Enable secure user sessions to prevent unauthorized access

  Users need protection from session hijacking vulnerabilities.

  * Add JWT authentication with token validation
  * Integrate OAuth2 flow for social login providers
  * Protect routes with authentication middleware

  Authors and coauthors:
    - {author_name} <{author_email}>
  ```

  ```
  FIX: Eliminate memory leak to prevent application crashes

  Production servers were crashing due to unbounded memory growth.

  * Fix WebSocket cleanup to properly close abandoned connections
  * Add connection pooling with automatic timeout handling

  Authors and coauthors:
    - {author_name} <{author_email}>
  ```

  Git diff:
  {diff}